// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBpLHjbVpi2BHT-wcMGzNwyVIS5aNZTi4k',
    appId: '1:1067046020767:web:f02c978fc47b1de3bf24aa',
    messagingSenderId: '1067046020767',
    projectId: 'bookshare-app-4bcf9',
    authDomain: 'bookshare-app-4bcf9.firebaseapp.com',
    storageBucket: 'bookshare-app-4bcf9.firebasestorage.app',
    measurementId: 'G-RKJFSY02WY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_72mSdFLcrHLAt8Ks1RF6nrG4hDCZCTA',
    appId: '1:1067046020767:android:8aa3a1753022f196bf24aa',
    messagingSenderId: '1067046020767',
    projectId: 'bookshare-app-4bcf9',
    storageBucket: 'bookshare-app-4bcf9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCv8Wsu-IoUltVl2b4ofvpKRySNdBwWq2k',
    appId: '1:1067046020767:ios:c0152b2c86d97430bf24aa',
    messagingSenderId: '1067046020767',
    projectId: 'bookshare-app-4bcf9',
    storageBucket: 'bookshare-app-4bcf9.firebasestorage.app',
    iosBundleId: 'com.example.bookshare',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCv8Wsu-IoUltVl2b4ofvpKRySNdBwWq2k',
    appId: '1:1067046020767:ios:c0152b2c86d97430bf24aa',
    messagingSenderId: '1067046020767',
    projectId: 'bookshare-app-4bcf9',
    storageBucket: 'bookshare-app-4bcf9.firebasestorage.app',
    iosBundleId: 'com.example.bookshare',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBpLHjbVpi2BHT-wcMGzNwyVIS5aNZTi4k',
    appId: '1:1067046020767:web:ea14e30a3eaf58e6bf24aa',
    messagingSenderId: '1067046020767',
    projectId: 'bookshare-app-4bcf9',
    authDomain: 'bookshare-app-4bcf9.firebaseapp.com',
    storageBucket: 'bookshare-app-4bcf9.firebasestorage.app',
    measurementId: 'G-C393B053HF',
  );

}